### ISSUE TITLE
开多达64安卓实例时，性能严重卡顿

### ISSUE THREAD

**Issue by wormwang** [Requiem4Eternity/Appstream#65]
strace -p 37623 //CPU占用偏高到45%的 安卓实例内进程

clock_gettime(CLOCK_MONOTONIC, {tv_sec=2044246794711462779, tv_nsec=17859950733902938112}) = 0
epoll_pwait(15, [{EPOLLIN, {u32=45, u64=45}}], 16, 72, NULL, 8) = 1
recvfrom(45, "nysv\0\0\0\0\246x\21yKt\0\0(c9\0ntex", 2400, MSG_DONTWAIT, NULL, NULL) = 24
recvfrom(45, 0xffa5fa58, 2400, MSG_DONTWAIT, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)

仍然报：Resource temporarily unavailable

**Comment by warlice** [comment]
以下是资源上限和当前资源使用检查：
**线程数：**
ps -eL |wc -l
127740
root@k8snode233:/home/motech# cat /proc/sys/kernel/threads-max 
1029336
root@k8snode233:/home/motech# cat /proc/sys/vm/max_map_count 
65530000

**进程数**
ps -ef |wc -l
5950
root@k8snode233:/home/motech# cat /proc/sys/kernel/pid_max 
4194303
 **内存**
free -mh
              total        used        free      shared  buff/cache   available
Mem:           125G         69G        265M        140M         56G         55G
Swap:          2.0G        831M        1.2G

**文件**
root@k8snode233:/home/motech# cat /proc/sys/fs/file-nr
436736	0	5242880
root@k8snode233:/home/motech# cat /proc/sys/fs/file-max
5242880
root@k8snode233:/home/motech# ulimit  -n
2097152

**Comment by wormwang** [comment]
这个进程的活动信息看着是正常，不是卡顿现象根源
