### ISSUE TITLE
5.25-5.31 服务器运行故障统计

### ISSUE THREAD

**Issue by warlice** [Requiem4Eternity/Appstream#88]
229 5.25 22:12 ；5.26 11:22 各发生一次146故障。
https://github.com/Requiem4Eternity/Appstream/issues/77#issuecomment-496051284

**Comment by warlice** [comment]
绿屏统计：229 ：card1； 230： card1；233： card1；235：card1,；238：card0

**Comment by fainted** [comment]
146故障统计
- 230机器 https://github.com/Requiem4Eternity/Appstream/issues/77#issuecomment-496065029
  - 5/25 01:02
  - 5/26 03:52
  - 5/26 21:48
- 232机器 https://github.com/Requiem4Eternity/Appstream/issues/77#issuecomment-496065206
  - 5/26 06:02
  - 5/26 07:07
  - 5/26 09:25
  - 5/26 09:48
  - 5/26 12:58
  - 5/26 19:02
- 233机器 https://github.com/Requiem4Eternity/Appstream/issues/77#issuecomment-496065879
  - 5/25 16:00
  - 5/25 16:01
  - 5/26 15:24
  - 5/26 19:42
  - 5/27 06:17
- 234机器 https://github.com/Requiem4Eternity/Appstream/issues/77#issuecomment-496066239
  - 5/25 17:21
  - 5/25 18:20
- 235机器 https://github.com/Requiem4Eternity/Appstream/issues/77#issuecomment-496066445
  - 5/25 01:44
  - 5/26 20:44
- 236机器 https://github.com/Requiem4Eternity/Appstream/issues/77#issuecomment-496066485
  - 5/27 01:19
- 237机器 https://github.com/Requiem4Eternity/Appstream/issues/77#issuecomment-496066891
  - 5/26 15:37
- 239机器 https://github.com/Requiem4Eternity/Appstream/issues/77#issuecomment-496067086
  - 5/25 01:00
  - 5/25 09:19
  - 5/25 10:05
